# The plugin manifest describes the plugin and its capabilities.
# At the very least it must contain these three fields:
name = "tree-sitter-plugin"
version = "0.0"
exec_path = "./bin/xi-tree-sitter-plugin"
